// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	backupCreate: () => typedError<AppResult<BackupSummary | null>, null>(__TAURI_INVOKE("backup_create")),
	backupPrepareRestore: () => typedError<AppResult<BackupRestoreCandidate | null>, null>(__TAURI_INVOKE("backup_prepare_restore")),
	backupRestore: (candidateId: string) => typedError<AppResult<boolean>, null>(__TAURI_INVOKE("backup_restore", { candidateId })),
	backupRestoreStatus: () => __TAURI_INVOKE<AppResult<BackupRestoreReceipt | null>>("backup_restore_status"),
	systemStatus: () => __TAURI_INVOKE<AppResult<SystemStatus>>("system_status"),
	profileList: () => __TAURI_INVOKE<AppResult<ProfileOverview>>("profile_list"),
	profileCreate: (input: ProfileNameInput) => __TAURI_INVOKE<AppResult<ProfileOverview>>("profile_create", { input }),
	profileRename: (input: ProfileRenameInput) => __TAURI_INVOKE<AppResult<ProfileOverview>>("profile_rename", { input }),
	profileSelect: (profileId: string) => __TAURI_INVOKE<AppResult<ProfileOverview>>("profile_select", { profileId }),
	libraryContext: () => __TAURI_INVOKE<AppResult<LibraryContext>>("library_context"),
	problemDetail: (problemId: string) => __TAURI_INVOKE<AppResult<ProblemDetail>>("problem_detail", { problemId }),
	problemChangeStatus: (input: ProblemStatusInput) => __TAURI_INVOKE<AppResult<number>>("problem_change_status", { input }),
	problemList: (status: ProblemStatusFilter, search: string | null) => __TAURI_INVOKE<AppResult<ProblemSummary[]>>("problem_list", { status, search }),
	problemUpdate: (input: ProblemUpdateInput) => __TAURI_INVOKE<AppResult<boolean>>("problem_update", { input }),
	legacyScan: () => __TAURI_INVOKE<AppResult<LegacyScanReport | null>>("legacy_scan"),
	reviewQueue: () => __TAURI_INVOKE<AppResult<ReviewQueueOverview>>("review_queue"),
	reviewManualStart: (input: ReviewManualStartInput) => __TAURI_INVOKE<AppResult<ReviewQueueOverview>>("review_manual_start", { input }),
	reviewSubmit: (input: ReviewSubmitInput) => __TAURI_INVOKE<AppResult<ReviewSubmission>>("review_submit", { input }),
	dashboardOverview: (utcOffsetMinutes: number) => __TAURI_INVOKE<AppResult<DashboardOverview>>("dashboard_overview", { utcOffsetMinutes }),
	reportSummary: () => __TAURI_INVOKE<AppResult<ReportSummary>>("report_summary"),
	settingsOverview: () => __TAURI_INVOKE<AppResult<SettingsOverview>>("settings_overview"),
	subjectPreferencesGet: () => __TAURI_INVOKE<AppResult<SubjectPreferences>>("subject_preferences_get"),
	subjectPreferencesSave: (input: SubjectPreferencesInput) => __TAURI_INVOKE<AppResult<SubjectPreferences>>("subject_preferences_save", { input }),
	exportCandidates: (source: ExportCandidateSource) => __TAURI_INVOKE<AppResult<ExportCandidate[]>>("export_candidates", { source }),
	exportList: () => __TAURI_INVOKE<AppResult<ExportSnapshotSummary[]>>("export_list"),
	exportTrashList: () => __TAURI_INVOKE<AppResult<DeletedExportSnapshotSummary[]>>("export_trash_list"),
	exportCreate: (input: ExportCreateInput) => __TAURI_INVOKE<AppResult<ExportSnapshotSummary>>("export_create", { input }),
	exportGenerate: (snapshotId: string) => __TAURI_INVOKE<AppResult<GeneratedExportSummary | null>>("export_generate", { snapshotId }),
	exportDelete: (snapshotId: string) => __TAURI_INVOKE<AppResult<boolean>>("export_delete", { snapshotId }),
	exportRestore: (snapshotId: string) => __TAURI_INVOKE<AppResult<boolean>>("export_restore", { snapshotId }),
	captureBatchCreate: (input: CaptureBatchCreateInput) => __TAURI_INVOKE<AppResult<CaptureBatchSummary>>("capture_batch_create", { input }),
	captureBatchList: () => __TAURI_INVOKE<AppResult<CaptureBatchSummary[]>>("capture_batch_list"),
	captureBatchDetail: (batchId: string) => __TAURI_INVOKE<AppResult<CaptureBatchDetail>>("capture_batch_detail", { batchId }),
	captureBatchUpdate: (input: CaptureBatchUpdateInput) => __TAURI_INVOKE<AppResult<CaptureBatchSummary>>("capture_batch_update", { input }),
	captureBatchAssignSubject: (input: CaptureBatchSubjectInput) => __TAURI_INVOKE<AppResult<CaptureBatchDetail>>("capture_batch_assign_subject", { input }),
	captureBatchDiscard: (batchId: string) => __TAURI_INVOKE<AppResult<boolean>>("capture_batch_discard", { batchId }),
	captureImportSelect: (batchId: string) => __TAURI_INVOKE<AppResult<CaptureImportReport>>("capture_import_select", { batchId }),
	captureImportBytes: (input: CaptureImportBytesInput) => __TAURI_INVOKE<AppResult<CaptureItemSummary>>("capture_import_bytes", { input }),
	captureItemPreview: (batchId: string, itemId: string) => __TAURI_INVOKE<AppResult<CaptureItemPreview>>("capture_item_preview", { batchId, itemId }),
	captureItemRemove: (batchId: string, expectedRevision: number, itemId: string) => __TAURI_INVOKE<AppResult<CaptureBatchDetail>>("capture_item_remove", { batchId, expectedRevision, itemId }),
	captureLayoutApply: (input: CaptureLayoutInput) => __TAURI_INVOKE<AppResult<CaptureBatchDetail>>("capture_layout_apply", { input }),
	captureItemMove: (input: CaptureItemMoveInput) => __TAURI_INVOKE<AppResult<CaptureBatchDetail>>("capture_item_move", { input }),
	captureItemStageRole: (input: CaptureItemStageRoleInput) => __TAURI_INVOKE<AppResult<CaptureBatchDetail>>("capture_item_stage_role", { input }),
	captureCardMerge: (input: CaptureCardMergeInput) => __TAURI_INVOKE<AppResult<CaptureBatchDetail>>("capture_card_merge", { input }),
	captureDraftDelete: (batchId: string, expectedRevision: number, draftId: string) => __TAURI_INVOKE<AppResult<CaptureBatchDetail>>("capture_draft_delete", { batchId, expectedRevision, draftId }),
	captureDraftUpdate: (input: CaptureDraftUpdateInput) => __TAURI_INVOKE<AppResult<CaptureBatchDetail>>("capture_draft_update", { input }),
	captureCommitReady: (batchId: string, expectedRevision: number) => __TAURI_INVOKE<AppResult<CaptureCommitReport>>("capture_commit_ready", { batchId, expectedRevision }),
	captureLanAddresses: () => __TAURI_INVOKE<AppResult<CaptureLanAddress[]>>("capture_lan_addresses"),
	captureLanPreflight: () => __TAURI_INVOKE<AppResult<CaptureLanPreflight>>("capture_lan_preflight"),
	captureLanFirewallRepair: () => __TAURI_INVOKE<AppResult<CaptureLanPreflight>>("capture_lan_firewall_repair"),
	captureLanStart: (input: CaptureLanStartInput) => __TAURI_INVOKE<AppResult<CaptureLanSession>>("capture_lan_start", { input }),
	captureLanStatus: () => __TAURI_INVOKE<AppResult<CaptureLanSession | null>>("capture_lan_status"),
	captureLanStop: () => __TAURI_INVOKE<AppResult<boolean>>("capture_lan_stop"),
};

/* Types */
export type AppError = {
	code: string,
	userMessage: string,
	retryable: boolean,
	diagnosticId: string,
};

export type AppResult<T> = ({ ok: boolean; data: T }) & { error?: never } | ({ ok: boolean; error: AppError }) & { data?: never };

export type BackupRestoreCandidate = {
	id: string,
	summary: BackupSummary,
	expiresAtUtcMs: number | null,
};

export type BackupRestoreReceipt = {
	status: string,
	label: string,
	finishedAtUtcMs: number | null,
};

export type BackupSummary = {
	formatVersion: number,
	createdAtUtcMs: number | null,
	assetCount: number,
	encryptedBytes: number | null,
	label: string,
	readyForRestore: boolean,
};

export type CaptureBatchCreateInput = {
	subject: string,
};

export type CaptureBatchDetail = {
	batch: CaptureBatchSummary,
	items: CaptureItemSummary[],
	drafts: CaptureDraftSummary[],
	unassignedItemIds: string[],
};

export type CaptureBatchState = "collecting" | "organizing" | "completed";

export type CaptureBatchSubjectInput = {
	batchId: string,
	expectedRevision: number,
	subject: string,
};

export type CaptureBatchSummary = {
	id: string,
	subject: string,
	state: CaptureBatchState,
	itemCount: number,
	draftCount: number,
	readyCount: number,
	updatedAtUtcMs: number | null,
	revision: number,
};

export type CaptureBatchUpdateInput = {
	batchId: string,
	expectedRevision: number,
	subject: string,
	finishCollecting: boolean,
};

export type CaptureCardMergeInput = {
	batchId: string,
	expectedRevision: number,
	targetDraftId: string | null,
	itemIds: string[],
	newDraftSubject: string | null,
};

export type CaptureCommitReport = {
	committedProblemIds: string[],
	committedCount: number,
	remainingDraftCount: number,
};

export type CaptureDraftSummary = {
	id: string,
	position: number,
	subject: string,
	tags: string[],
	note: string,
	questionItemIds: string[],
	answerItemIds: string[],
	ready: boolean,
};

export type CaptureDraftUpdateInput = {
	batchId: string,
	expectedRevision: number,
	draftId: string,
	subject: string,
	tags: string[],
	note: string,
};

export type CaptureImportBytesInput = {
	batchId: string,
	clientUploadId: string,
	sourceName: string,
	sourceSequence: number | null,
	bytes: number[],
};

export type CaptureImportReport = {
	importedItems: CaptureItemSummary[],
	importedCount: number,
};

export type CaptureItemMoveInput = {
	batchId: string,
	expectedRevision: number,
	itemId: string,
	targetDraftId: string | null,
	targetRole: string | null,
	targetPosition: number,
};

export type CaptureItemPreview = {
	itemId: string,
	mediaType: string,
	dataUrl: string,
};

export type CaptureItemStageRoleInput = {
	batchId: string,
	expectedRevision: number,
	itemId: string,
	stagedRole: string,
};

export type CaptureItemSummary = {
	id: string,
	sourceName: string,
	sourceSequence: number,
	mediaType: string,
	byteLength: number | null,
	width: number,
	height: number,
	stagedRole: string,
	draftId: string | null,
	role: string | null,
	position: number | null,
};

export type CaptureLanAddress = {
	label: string,
	address: string,
};

export type CaptureLanFirewallRuleState = "ready" | "missing" | "invalid" | "unavailable";

export type CaptureLanPreflight = {
	supported: boolean,
	activeProfiles: CaptureLanProfile[],
	firewallRule: CaptureLanFirewallRuleState,
	canStart: boolean,
	needsNetworkChange: boolean,
	needsFirewallRepair: boolean,
};

export type CaptureLanProfile = "domain" | "private" | "public";

export type CaptureLanSession = {
	sessionId: string,
	batchId: string,
	qrSvgDataUrl: string,
	selectedAddress: string,
	expiresAtUtcMs: number | null,
	receivedItemCount: number,
	receivedBytes: number | null,
};

export type CaptureLanStartInput = {
	batchId: string,
	selectedAddress: string | null,
};

export type CaptureLayoutInput = {
	batchId: string,
	expectedRevision: number,
	mode: CaptureLayoutMode,
	questionImagesPerDraft: number,
	answerImagesPerDraft: number,
	splitIndex: number | null,
};

export type CaptureLayoutMode = "alternating" | "split" | "questions_only" | "manual";

export type DailyActivity = {
	dayStartUtcMs: number | null,
	reviewCount: number,
	durationMs: number | null,
};

export type DashboardOverview = {
	profileName: string,
	activeProblemCount: number,
	dueProblemCount: number,
	reviewedTodayCount: number,
	rememberedRate30Days: number | null,
	currentStreakDays: number,
	pendingCaptureBatchCount: number,
	pendingCaptureItemCount: number,
};

export type DeletedExportSnapshotSummary = {
	snapshot: ExportSnapshotSummary,
	deletedAtUtcMs: number | null,
	purgeAfterUtcMs: number | null,
};

export type ExportCandidate = {
	id: string,
	subject: string,
	note: string,
	questionAssetCount: number,
	answerAssetCount: number,
	dueAtUtcMs: number | null,
	reviewCount: number,
};

export type ExportCandidateSource = "due" | "latest_review_session" | "all_active";

export type ExportCreateInput = {
	title: string,
	problemIds: string[],
	layout: ExportLayout,
};

export type ExportLayout = "question_answer_alternating" | "questions_then_answers" | "original_image_folder";

export type ExportSnapshotSummary = {
	id: string,
	title: string,
	problemCount: number,
	layout: ExportLayout,
	createdAtUtcMs: number | null,
};

export type FsrsRating = "again" | "hard" | "good" | "easy";

export type GeneratedExportSummary = {
	snapshotId: string,
	outputName: string,
	problemCount: number,
	layout: ExportLayout,
};

export type LegacyIssue = {
	code: string,
	member: string,
	recordId: string | null,
	detail: string,
};

export type LegacyScanReport = {
	members: number,
	metadataRecords: number,
	existingAssets: number,
	trainingRecords: number,
	frozenRecords: number,
	duplicateAssets: number,
	truncated: boolean,
	issues: LegacyIssue[],
};

export type LibraryContext = {
	profileId: string,
	profileName: string,
	storage: string,
};

export type ProblemAssetPreview = {
	id: string,
	role: string,
	position: number,
	mediaType: string,
	dataUrl: string,
};

export type ProblemDetail = {
	id: string,
	subject: string,
	note: string,
	status: string,
	timeLimitSeconds: number | null,
	updatedAtUtcMs: number | null,
	assets: ProblemAssetPreview[],
};

export type ProblemStatusFilter = "active" | "archived" | "trashed";

export type ProblemStatusInput = {
	problemIds: string[],
	targetStatus: ProblemStatusFilter,
};

export type ProblemSummary = {
	id: string,
	subject: string,
	note: string,
	status: string,
	questionAssetCount: number,
	answerAssetCount: number,
	updatedAtUtcMs: number | null,
};

export type ProblemUpdateInput = {
	problemId: string,
	subject: string,
	note: string,
	timeLimitSeconds: number | null,
};

export type ProfileNameInput = {
	name: string,
};

export type ProfileOverview = {
	activeProfileId: string,
	profiles: ProfileSummary[],
};

export type ProfileRenameInput = {
	profileId: string,
	name: string,
};

export type ProfileSummary = {
	id: string,
	name: string,
	createdAtUtcMs: number | null,
	updatedAtUtcMs: number | null,
	revision: number,
};

export type ReportSummary = {
	activeProblemCount: number,
	dueProblemCount: number,
	reviewCount: number,
	rememberedRate: number | null,
	totalDurationMs: number | null,
	currentStreakDays: number,
	dailyActivity: DailyActivity[],
	subjectActivity: SubjectActivity[],
};

export type ReviewManualStartInput = {
	problemIds: string[],
};

export type ReviewQueueItem = {
	problemId: string,
	dueAtUtcMs: number | null,
	reviewCount: number,
};

export type ReviewQueueOverview = {
	sessionId: string | null,
	mode: string,
	resumed: boolean,
	completedCount: number,
	totalCount: number,
	items: ReviewQueueItem[],
};

export type ReviewSubmission = {
	eventId: string,
	problemId: string,
	rating: string,
	dueAtUtcMs: number | null,
	stability: number | null,
	difficulty: number | null,
	algorithmVersion: string,
	parameterVersion: string,
};

export type ReviewSubmitInput = {
	problemId: string,
	rating: FsrsRating,
	durationMs: number,
};

export type SettingsOverview = {
	activeProblemCount: number,
	archivedProblemCount: number,
	trashedProblemCount: number,
	pendingOperationCount: number,
	failedOperationCount: number,
	unresolvedConflictCount: number,
	localEncryptionReady: boolean,
	cloudSyncConfigured: boolean,
};

export type SubjectActivity = {
	subject: string,
	problemCount: number,
	reviewCount: number,
};

export type SubjectPreferences = {
	enabledSubjects: string[],
	customSubjects: string[],
	captureSoundEnabled: boolean,
};

export type SubjectPreferencesInput = {
	enabledSubjects: string[],
	customSubjects: string[],
	captureSoundEnabled: boolean,
};

export type SystemStatus = {
	appVersion: string,
	storage: string,
	sync: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}
