// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	backupCreate: () => typedError<AppResult<BackupSummary | null>, null>(__TAURI_INVOKE("backup_create")),
	backupValidate: () => typedError<AppResult<BackupSummary | null>, null>(__TAURI_INVOKE("backup_validate")),
	systemStatus: () => __TAURI_INVOKE<AppResult<SystemStatus>>("system_status"),
	libraryContext: () => __TAURI_INVOKE<AppResult<LibraryContext>>("library_context"),
	problemDetail: (problemId: string) => __TAURI_INVOKE<AppResult<ProblemDetail>>("problem_detail", { problemId }),
	problemChangeStatus: (input: ProblemStatusInput) => __TAURI_INVOKE<AppResult<number>>("problem_change_status", { input }),
	problemList: (status: ProblemStatusFilter, search: string | null) => __TAURI_INVOKE<AppResult<ProblemSummary[]>>("problem_list", { status, search }),
	problemUpdate: (input: ProblemUpdateInput) => __TAURI_INVOKE<AppResult<boolean>>("problem_update", { input }),
	legacyScan: () => __TAURI_INVOKE<AppResult<LegacyScanReport | null>>("legacy_scan"),
	reviewQueue: (problemId: string | null) => __TAURI_INVOKE<AppResult<ReviewQueueItem[]>>("review_queue", { problemId }),
	reviewSubmit: (input: ReviewSubmitInput) => __TAURI_INVOKE<AppResult<ReviewSubmission>>("review_submit", { input }),
	reportSummary: () => __TAURI_INVOKE<AppResult<ReportSummary>>("report_summary"),
	settingsOverview: () => __TAURI_INVOKE<AppResult<SettingsOverview>>("settings_overview"),
	exportList: () => __TAURI_INVOKE<AppResult<ExportSnapshotSummary[]>>("export_list"),
	exportTrashList: () => __TAURI_INVOKE<AppResult<DeletedExportSnapshotSummary[]>>("export_trash_list"),
	exportCreate: (input: ExportCreateInput) => __TAURI_INVOKE<AppResult<ExportSnapshotSummary>>("export_create", { input }),
	exportGenerate: (snapshotId: string) => __TAURI_INVOKE<AppResult<GeneratedExportSummary | null>>("export_generate", { snapshotId }),
	exportDelete: (snapshotId: string) => __TAURI_INVOKE<AppResult<boolean>>("export_delete", { snapshotId }),
	exportRestore: (snapshotId: string) => __TAURI_INVOKE<AppResult<boolean>>("export_restore", { snapshotId }),
	captureCommit: (input: CaptureCommitInput) => __TAURI_INVOKE<AppResult<CaptureCommitOutput>>("capture_commit", { input }),
	captureList: () => __TAURI_INVOKE<AppResult<StagedAsset[]>>("capture_list"),
	captureRemove: (stagedAssetId: string) => __TAURI_INVOKE<AppResult<boolean>>("capture_remove", { stagedAssetId }),
	captureSelect: (role: string) => __TAURI_INVOKE<AppResult<StagedAsset[]>>("capture_select", { role }),
};

/* Types */
export type AppError = {
	code: string,
	userMessage: string,
	retryable: boolean,
	diagnosticId: string,
};

export type AppResult<T> = ({ ok: boolean; data: T }) & { error?: never } | ({ ok: boolean; error: AppError }) & { data?: never };

export type BackupSummary = {
	formatVersion: number,
	createdAtUtcMs: number | null,
	assetCount: number,
	encryptedBytes: number | null,
	label: string,
	readyForRestore: boolean,
};

export type CaptureCommitInput = {
	subject: string,
	note: string,
	stagedAssetIds: string[],
};

export type CaptureCommitOutput = {
	problemId: string,
};

export type DailyActivity = {
	dayStartUtcMs: number | null,
	reviewCount: number,
	durationMs: number | null,
};

export type DeletedExportSnapshotSummary = {
	snapshot: ExportSnapshotSummary,
	deletedAtUtcMs: number | null,
	purgeAfterUtcMs: number | null,
};

export type ExportCreateInput = {
	title: string,
	problemIds: string[],
	layout: ExportLayout,
};

export type ExportLayout = "question_answer_alternating" | "questions_then_answers" | "original_image_folder";

export type ExportSnapshotSummary = {
	id: string,
	title: string,
	problemCount: number,
	layout: ExportLayout,
	createdAtUtcMs: number | null,
};

export type FsrsRating = "again" | "hard" | "good" | "easy";

export type GeneratedExportSummary = {
	snapshotId: string,
	outputName: string,
	problemCount: number,
	layout: ExportLayout,
};

export type LegacyIssue = {
	code: string,
	member: string,
	recordId: string | null,
	detail: string,
};

export type LegacyScanReport = {
	members: number,
	metadataRecords: number,
	existingAssets: number,
	trainingRecords: number,
	frozenRecords: number,
	duplicateAssets: number,
	truncated: boolean,
	issues: LegacyIssue[],
};

export type LibraryContext = {
	profileId: string,
	profileName: string,
	storage: string,
};

export type ProblemAssetPreview = {
	id: string,
	role: string,
	position: number,
	mediaType: string,
	dataUrl: string,
};

export type ProblemDetail = {
	id: string,
	subject: string,
	note: string,
	status: string,
	updatedAtUtcMs: number | null,
	assets: ProblemAssetPreview[],
};

export type ProblemStatusFilter = "active" | "archived" | "trashed";

export type ProblemStatusInput = {
	problemIds: string[],
	targetStatus: ProblemStatusFilter,
};

export type ProblemSummary = {
	id: string,
	subject: string,
	note: string,
	status: string,
	questionAssetCount: number,
	answerAssetCount: number,
	updatedAtUtcMs: number | null,
};

export type ProblemUpdateInput = {
	problemId: string,
	subject: string,
	note: string,
};

export type ReportSummary = {
	activeProblemCount: number,
	dueProblemCount: number,
	reviewCount: number,
	rememberedRate: number | null,
	totalDurationMs: number | null,
	currentStreakDays: number,
	dailyActivity: DailyActivity[],
	subjectActivity: SubjectActivity[],
};

export type ReviewQueueItem = {
	problemId: string,
	dueAtUtcMs: number | null,
	reviewCount: number,
};

export type ReviewSubmission = {
	eventId: string,
	problemId: string,
	rating: string,
	dueAtUtcMs: number | null,
	stability: number | null,
	difficulty: number | null,
	algorithmVersion: string,
	parameterVersion: string,
};

export type ReviewSubmitInput = {
	problemId: string,
	rating: FsrsRating,
	durationMs: number,
};

export type SettingsOverview = {
	activeProblemCount: number,
	archivedProblemCount: number,
	trashedProblemCount: number,
	pendingOperationCount: number,
	failedOperationCount: number,
	unresolvedConflictCount: number,
	localEncryptionReady: boolean,
	cloudSyncConfigured: boolean,
};

export type StagedAsset = {
	id: string,
	fileName: string,
	role: string,
	mediaType: string,
	byteLength: number | null,
	width: number,
	height: number,
};

export type SubjectActivity = {
	subject: string,
	problemCount: number,
	reviewCount: number,
};

export type SystemStatus = {
	appVersion: string,
	storage: string,
	sync: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}
