// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	systemStatus: () => __TAURI_INVOKE<AppResult<SystemStatus>>("system_status"),
};

/* Types */
export type AppError = {
	code: string,
	userMessage: string,
	retryable: boolean,
	diagnosticId: string,
};

export type AppResult<T> = ({ ok: boolean; data: T }) & { error?: never } | ({ ok: boolean; error: AppError }) & { data?: never };

export type SystemStatus = {
	appVersion: string,
	storage: string,
	sync: string,
};
